# Generated by Django 5.1.7 on 2025-03-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_tag_task_collaborators_task_priority_matrix_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="historicaltask",
            name="category",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="fileattachment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="historicaltask",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="subtask",
            name="task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="taskdependency",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="dependency",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="dependencies",
        ),
        migrations.DeleteModel(
            name="TaskTemplate",
        ),
        migrations.RemoveField(
            model_name="task",
            name="collaborators",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="task",
            name="priority_matrix",
        ),
        migrations.RemoveField(
            model_name="task",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="task",
            name="recurrence",
        ),
        migrations.RemoveField(
            model_name="task",
            name="time_estimated",
        ),
        migrations.RemoveField(
            model_name="task",
            name="time_spent",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="FileAttachment",
        ),
        migrations.DeleteModel(
            name="HistoricalTask",
        ),
        migrations.DeleteModel(
            name="Subtask",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="TaskDependency",
        ),
    ]
