# Generated by Django 5.1.7 on 2025-08-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-last_updated"]},
        ),
    ]
