# Generated by Django 5.1.7 on 2025-09-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="file",
        ),
    ]
